//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace variant_2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string student_ID_number { get; set; }
        public string full_name { get; set; }
        public Nullable<int> group_id { get; set; }
        public System.DateTime birth_date { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
